'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17626
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Data
Imports System.Collections.Generic
Imports System.Reflection
Imports System.Linq
Imports System.Linq.Expressions
Imports System.ComponentModel
Imports System

Namespace Sample.Models

    <Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="Northwind")>
    Public Partial Class NorthwindDataContext
        Inherits System.Data.Linq.DataContext

        Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New System.Data.Linq.Mapping.AttributeMappingSource()

'#Region "Extensibility Method Definitions"
        Partial Private Sub OnCreated()
        End Sub

'#End Region
        Public Sub New()
            MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings(CStr(("NorthwindConnectionString"))).ConnectionString, Sample.Models.NorthwindDataContext.mappingSource)
            Me.OnCreated()
        End Sub

        Public Sub New(ByVal connection As String)
            MyBase.New(connection, Sample.Models.NorthwindDataContext.mappingSource)
            Me.OnCreated()
        End Sub

        Public Sub New(ByVal connection As System.Data.IDbConnection)
            MyBase.New(connection, Sample.Models.NorthwindDataContext.mappingSource)
            Me.OnCreated()
        End Sub

        Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
            MyBase.New(connection, mappingSource)
            Me.OnCreated()
        End Sub

        Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
            MyBase.New(connection, mappingSource)
            Me.OnCreated()
        End Sub

        Public ReadOnly Property Customers As System.Data.Linq.Table(Of Sample.Models.Customer)
            Get
                Return Me.GetTable(Of Sample.Models.Customer)()
            End Get
        End Property
    End Class

    <Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.Customers")>
    Public Partial Class Customer

        Private _CustomerID As String

        Private _CompanyName As String

        Private _ContactName As String

        Private _ContactTitle As String

        Private _Address As String

        Private _City As String

        Private _Region As String

        Private _PostalCode As String

        Private _Country As String

        Private _Phone As String

        Private _Fax As String

        Public Sub New()
        End Sub

        <Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CustomerID", DbType:="NChar(5) NOT NULL", CanBeNull:=False)>
        Public Property CustomerID As String
            Get
                Return Me._CustomerID
            End Get

            Set(ByVal value As String)
                If(Not Equals(Me._CustomerID, value)) Then
                    Me._CustomerID = value
                End If
            End Set
        End Property

        <Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CompanyName", DbType:="NVarChar(40) NOT NULL", CanBeNull:=False)>
        Public Property CompanyName As String
            Get
                Return Me._CompanyName
            End Get

            Set(ByVal value As String)
                If(Not Equals(Me._CompanyName, value)) Then
                    Me._CompanyName = value
                End If
            End Set
        End Property

        <Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ContactName", DbType:="NVarChar(30)")>
        Public Property ContactName As String
            Get
                Return Me._ContactName
            End Get

            Set(ByVal value As String)
                If(Not Equals(Me._ContactName, value)) Then
                    Me._ContactName = value
                End If
            End Set
        End Property

        <Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ContactTitle", DbType:="NVarChar(30)")>
        Public Property ContactTitle As String
            Get
                Return Me._ContactTitle
            End Get

            Set(ByVal value As String)
                If(Not Equals(Me._ContactTitle, value)) Then
                    Me._ContactTitle = value
                End If
            End Set
        End Property

        <Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Address", DbType:="NVarChar(60)")>
        Public Property Address As String
            Get
                Return Me._Address
            End Get

            Set(ByVal value As String)
                If(Not Equals(Me._Address, value)) Then
                    Me._Address = value
                End If
            End Set
        End Property

        <Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_City", DbType:="NVarChar(15)")>
        Public Property City As String
            Get
                Return Me._City
            End Get

            Set(ByVal value As String)
                If(Not Equals(Me._City, value)) Then
                    Me._City = value
                End If
            End Set
        End Property

        <Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Region", DbType:="NVarChar(15)")>
        Public Property Region As String
            Get
                Return Me._Region
            End Get

            Set(ByVal value As String)
                If(Not Equals(Me._Region, value)) Then
                    Me._Region = value
                End If
            End Set
        End Property

        <Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PostalCode", DbType:="NVarChar(10)")>
        Public Property PostalCode As String
            Get
                Return Me._PostalCode
            End Get

            Set(ByVal value As String)
                If(Not Equals(Me._PostalCode, value)) Then
                    Me._PostalCode = value
                End If
            End Set
        End Property

        <Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Country", DbType:="NVarChar(15)")>
        Public Property Country As String
            Get
                Return Me._Country
            End Get

            Set(ByVal value As String)
                If(Not Equals(Me._Country, value)) Then
                    Me._Country = value
                End If
            End Set
        End Property

        <Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Phone", DbType:="NVarChar(24)")>
        Public Property Phone As String
            Get
                Return Me._Phone
            End Get

            Set(ByVal value As String)
                If(Not Equals(Me._Phone, value)) Then
                    Me._Phone = value
                End If
            End Set
        End Property

        <Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Fax", DbType:="NVarChar(24)")>
        Public Property Fax As String
            Get
                Return Me._Fax
            End Get

            Set(ByVal value As String)
                If(Not Equals(Me._Fax, value)) Then
                    Me._Fax = value
                End If
            End Set
        End Property
    End Class
End Namespace
